# Generated by Django 5.0.2 on 2024-02-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookflight',
            name='username_id',
            field=models.EmailField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bookhotel',
            name='username_id',
            field=models.EmailField(max_length=500),
        ),
    ]
