# Generated by Django 5.0.1 on 2024-02-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookflight',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bookflight',
            name='lon',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bookhotel',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bookhotel',
            name='lon',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='flights',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='flights',
            name='lon',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
