# Generated by Django 5.0.1 on 2024-02-21 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bookflight_lat_bookflight_lon_bookhotel_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flights',
            name='date',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='lon',
        ),
    ]
